# Generated by Django 3.2.9 on 2021-12-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_agent_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead',
            new_name='agent',
        ),
    ]
